// client/src/pages/Dashboard.tsx
import { cn } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { 
  Calendar, 
  Check, 
  Clock, 
  Pill, 
  Plus, 
  X, 
  Mic,
  MicOff,
  Sparkles,
  Send,
  ShoppingCart,
  Loader2
} from "lucide-react";
import { format } from "date-fns";
import { useState, useEffect, useRef } from "react";
import { useLocation } from "wouter";
import { useToast } from "@/hooks/use-toast";
import { useQueryClient } from "@tanstack/react-query";
import { useCurrentFamily, useFamilyMembers, useReminders, useMedicines, useMedicineLogs, useChores, useCreateReminder, useCreateMedicineLog } from "@/hooks/useData";
import * as api from "@/lib/api";

type Mode = 'OVERVIEW' | 'ADD_REMINDER' | 'ADD_CHORE';

interface ParsedItem {
  type: string;
  title: string;
  description?: string;
  dateTime?: string;
  points?: number;
}

declare global {
  interface Window {
    webkitSpeechRecognition: any;
    SpeechRecognition: any;
  }
}

export default function Dashboard() {
  const { toast } = useToast();
  const [, setLocation] = useLocation();
  const queryClient = useQueryClient();
  const family = useCurrentFamily();
  const { data: members = [] } = useFamilyMembers(family?.id);
  const { data: reminders = [], isLoading: remindersLoading } = useReminders(family?.id);
  const { data: medicines = [], isLoading: medsLoading } = useMedicines(family?.id);
  const { data: medicineLogs = [] } = useMedicineLogs(family?.id);
  const { data: chores = [], isLoading: choresLoading } = useChores(family?.id);
  const createReminder = useCreateReminder(family?.id);
  const createMedicineLog = useCreateMedicineLog(family?.id);
  
  const [mode, setMode] = useState<Mode>('OVERVIEW');
  const [quickActionsOpen, setQuickActionsOpen] = useState(false);
  const [showAllSchedule, setShowAllSchedule] = useState(false);
  
  const [smartInputText, setSmartInputText] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [speechSupported, setSpeechSupported] = useState(false);
  const [lastResult, setLastResult] = useState<{ success: boolean; message: string; items?: ParsedItem[] } | null>(null);
  const recognitionRef = useRef<any>(null);
  
  const [reminderForm, setReminderForm] = useState({ title: '', date: '', time: '', members: [] as string[] });
  const [choreForm, setChoreForm] = useState({ title: '', member: '', startTime: '', endDate: '' });

  useEffect(() => {
    const supported = 'webkitSpeechRecognition' in window || 'SpeechRecognition' in window;
    setSpeechSupported(supported);
    
    if (supported) {
      const SpeechRecognition = window.webkitSpeechRecognition || window.SpeechRecognition;
      recognitionRef.current = new SpeechRecognition();
      recognitionRef.current.continuous = true;
      recognitionRef.current.interimResults = true;
      recognitionRef.current.lang = 'en-US';
      
      recognitionRef.current.onresult = (event: any) => {
        let transcript = '';
        for (let i = event.resultIndex; i < event.results.length; i++) {
          transcript += event.results[i][0].transcript;
        }
        setSmartInputText(transcript);
      };
      
      recognitionRef.current.onerror = (event: any) => {
        console.error('Speech recognition error:', event.error);
        setIsRecording(false);
      };
      
      recognitionRef.current.onend = () => {
        setIsRecording(false);
      };
    }
    
    return () => {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
    };
  }, []);

  // Auto-close AI result notification after 1 second
  useEffect(() => {
    if (lastResult) {
      const timer = setTimeout(() => {
        setLastResult(null);
      }, 1000);
      return () => clearTimeout(timer);
    }
  }, [lastResult]);

  const toggleVoiceInput = () => {
    if (isRecording) {
      recognitionRef.current?.stop();
      setIsRecording(false);
    } else {
      setSmartInputText('');
      recognitionRef.current?.start();
      setIsRecording(true);
    }
  };

  const processSmartInput = async () => {
    if (!smartInputText.trim() || isProcessing) return;
    
    setIsProcessing(true);
    setLastResult(null);
    
    try {
      const data = await api.aiSchedule(smartInputText, family?.id);
      const totalCreated = data.choresCreated + data.remindersCreated + data.medicationsCreated + data.groceriesCreated;
      
      setLastResult({
        success: totalCreated > 0,
        message: data.message,
        items: data.items as ParsedItem[]
      });
      
      if (totalCreated > 0) {
        setSmartInputText('');
        queryClient.invalidateQueries({ queryKey: ['chores'] });
        queryClient.invalidateQueries({ queryKey: ['reminders'] });
        queryClient.invalidateQueries({ queryKey: ['medicines'] });
        queryClient.invalidateQueries({ queryKey: ['groceries'] });
        toast({
          title: "Items Created!",
          description: `Created ${totalCreated} item(s) from your input.`
        });
      }
    } catch (error) {
      setLastResult({
        success: false,
        message: 'Something went wrong. Make sure the API is configured.'
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const resetForms = () => {
    setReminderForm({ title: '', date: '', time: '', members: [] });
    setChoreForm({ title: '', member: '', startTime: '', endDate: '' });
    setMode('OVERVIEW');
  };

  const handleSaveReminder = () => {
    if (!family?.id) return;
    
    createReminder.mutate({
      title: reminderForm.title || "New Reminder",
      type: "Family",
      schedule: { type: "ONCE" },
      startTime: new Date(`${reminderForm.date}T${reminderForm.time || '12:00'}`),
      endTime: new Date(`${reminderForm.date}T${reminderForm.time || '13:00'}`),
    }, {
      onSuccess: () => {
        toast({ title: "Reminder Added", description: "Successfully scheduled." });
        resetForms();
      }
    });
  };

  if (mode === 'ADD_REMINDER') {
    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold text-[#D2691E]">Schedule Reminder</h1>
          <Button variant="ghost" onClick={() => setMode('OVERVIEW')}><X className="h-5 w-5" /></Button>
        </div>
        <Card className="border-none shadow-xl">
          <CardContent className="pt-6 space-y-4">
            <div className="grid gap-2">
              <Label>Reminder Title</Label>
              <Input placeholder="e.g. Soccer Practice" value={reminderForm.title} onChange={e => setReminderForm({...reminderForm, title: e.target.value})} data-testid="input-reminder-title" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label>Date</Label>
                <Input type="date" value={reminderForm.date} onChange={e => setReminderForm({...reminderForm, date: e.target.value})} data-testid="input-reminder-date" />
              </div>
              <div className="grid gap-2">
                <Label>Time</Label>
                <Input type="time" value={reminderForm.time} onChange={e => setReminderForm({...reminderForm, time: e.target.value})} data-testid="input-reminder-time" />
              </div>
            </div>
            <div className="grid gap-2">
              <Label>Family Members Involved</Label>
              <div className="flex flex-wrap gap-3 p-3 border rounded-lg bg-muted/30">
                {members.map(user => (
                  <div key={user.id} className="flex items-center gap-2">
                    <Checkbox 
                      id={`user-${user.id}`} 
                      checked={reminderForm.members.includes(user.id)}
                      onCheckedChange={(checked) => {
                        const newMembers = checked 
                          ? [...reminderForm.members, user.id]
                          : reminderForm.members.filter(id => id !== user.id);
                        setReminderForm({...reminderForm, members: newMembers});
                      }}
                    />
                    <label htmlFor={`user-${user.id}`} className="text-sm font-medium flex items-center gap-1">
                      <img src={user.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${user.name}`} className="h-5 w-5 rounded-full" />
                      {user.name}
                    </label>
                  </div>
                ))}
              </div>
            </div>
            <div className="flex gap-3 pt-4">
              <Button onClick={handleSaveReminder} className="flex-1 bg-[#D2691E] hover:bg-[#B8581A]" disabled={createReminder.isPending} data-testid="button-save-reminder">
                Save Reminder
              </Button>
              <Button variant="outline" className="flex-1" onClick={() => setMode('OVERVIEW')}>Cancel</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (mode === 'ADD_CHORE') {
    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold text-[#D2691E]">Assign Chore</h1>
          <Button variant="ghost" onClick={() => setMode('OVERVIEW')}><X className="h-5 w-5" /></Button>
        </div>
        <Card className="max-w-2xl mx-auto shadow-xl">
          <CardContent className="pt-6 space-y-4">
            <div className="grid gap-2">
              <Label>Chore Title</Label>
              <Input placeholder="e.g. Clean Kitchen" value={choreForm.title} onChange={e => setChoreForm({...choreForm, title: e.target.value})} />
            </div>
            <div className="grid gap-2">
              <Label>Assign To Family Member</Label>
              <div className="grid grid-cols-2 gap-2">
                {members.map(user => (
                  <Button 
                    key={user.id} 
                    variant={choreForm.member === user.id ? "default" : "outline"}
                    className={choreForm.member === user.id ? "bg-[#D2691E] hover:bg-[#B8581A]" : ""}
                    onClick={() => setChoreForm({...choreForm, member: user.id})}
                  >
                    <img src={user.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${user.name}`} className="h-4 w-4 rounded-full mr-2" />
                    {user.name}
                  </Button>
                ))}
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label>Start Time</Label>
                <Input type="time" value={choreForm.startTime} onChange={e => setChoreForm({...choreForm, startTime: e.target.value})} />
              </div>
              <div className="grid gap-2">
                <Label>End Date</Label>
                <Input type="date" value={choreForm.endDate} onChange={e => setChoreForm({...choreForm, endDate: e.target.value})} />
              </div>
            </div>
            <Button className="w-full bg-[#D2691E] hover:bg-[#B8581A]" onClick={() => {
              toast({ title: "Chore Assigned", description: "Task successfully delegated." });
              resetForms();
            }}>Save Assignment</Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const isLoading = remindersLoading || medsLoading || choresLoading;

  // Get today's date string in YYYY-MM-DD format for comparison
  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];
  today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  
  // Filter reminders for today
  const todayReminders = reminders.filter(reminder => {
    if (!reminder.startTime) return false;
    const reminderDate = new Date(reminder.startTime);
    return reminderDate >= today && reminderDate < tomorrow;
  });
  
  // Filter chores for today
  const todayChores = chores.filter(chore => {
    if (!chore.dueDate) return false;
    return chore.dueDate === todayStr;
  });
  
  // Create combined schedule items for today
  type ScheduleItem = { 
    id: string; 
    type: 'reminder' | 'chore' | 'medication'; 
    title: string; 
    time?: string;
    status?: string;
    assignedTo?: string;
    assignedName?: string;
    medicineId?: string;
    doses?: { time: string; taken: boolean }[];
  };
  
  // Check if a medication dose is taken today
  const isDoseTakenToday = (medicineId: string, scheduledTime: string) => {
    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    return medicineLogs.some(log => {
      const logDate = new Date(log.takenAt);
      logDate.setHours(0, 0, 0, 0);
      return log.medicineId === medicineId && 
             log.scheduledTime === scheduledTime && 
             logDate.getTime() === todayStart.getTime();
    });
  };

  // Check if medication is active today based on start/end dates
  const isMedicationActiveToday = (medicine: typeof medicines[0]) => {
    if (!medicine.active) return false;
    const todayStr = new Date().toISOString().split('T')[0];
    if (medicine.startDate && todayStr < medicine.startDate) return false;
    if (medicine.endDate && todayStr > medicine.endDate) return false;
    return true;
  };

  // Priority items: reminders and medications (shown first)
  // Create one entry per medication with all dose times and their statuses
  // Only show medications that are active today based on start/end dates
  const medicationItems: ScheduleItem[] = medicines.filter(m => isMedicationActiveToday(m)).map(m => {
    const schedule = m.schedule as { type?: string; times?: string[] } | null;
    const times = schedule?.times || [];
    const dosesInfo = times.map(time => ({
      time,
      taken: isDoseTakenToday(m.id, time)
    }));
    const allTaken = dosesInfo.every(d => d.taken);
    const someTaken = dosesInfo.some(d => d.taken);
    return {
      id: m.id,
      type: 'medication' as const,
      title: m.name,
      medicineId: m.id,
      doses: dosesInfo,
      status: allTaken ? 'TAKEN' : (someTaken ? 'PARTIAL' : 'PENDING')
    };
  });

  const priorityItems: ScheduleItem[] = [
    ...todayReminders.map(r => ({ 
      id: r.id, 
      type: 'reminder' as const, 
      title: r.title,
      time: r.startTime ? format(new Date(r.startTime), 'h:mm a') : undefined
    })),
    ...medicationItems
  ];
  
  // Chore items (shown on View All)
  const choreItems: ScheduleItem[] = todayChores.map(c => {
    const assignedMember = members.find(m => m.id === c.assignedTo);
    return { 
      id: c.id, 
      type: 'chore' as const, 
      title: c.title,
      status: c.status || undefined,
      assignedTo: c.assignedTo || undefined,
      assignedName: assignedMember?.name
    };
  });
  
  const displaySchedule = showAllSchedule ? [...priorityItems, ...choreItems] : priorityItems;

  const handleDoseClick = (medicineId: string, scheduledTime: string, alreadyTaken: boolean, e: React.MouseEvent) => {
    e.stopPropagation();
    if (alreadyTaken) {
      toast({ title: "Already taken", description: `This dose was already logged for today.` });
      return;
    }
    createMedicineLog.mutate(
      { medicineId, takenAt: new Date(), scheduledTime },
      {
        onSuccess: () => {
          toast({ title: "Dose logged!", description: `Marked ${scheduledTime} dose as taken.` });
        },
        onError: () => {
          toast({ title: "Error", description: "Failed to log dose. Please try again.", variant: "destructive" });
        }
      }
    );
  };

  return (
    <div className="flex flex-col gap-3 lg:gap-6">
      <div className="grid gap-3 lg:gap-6 md:grid-cols-2">
        <Card className="bg-gradient-to-br from-[#D2691E] to-[#E8954C] border-none shadow-lg shadow-[#D2691E]/20 text-white overflow-hidden relative">
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <Plus className="h-24 w-24 -mr-8 -mt-8 rotate-12" />
          </div>
          <CardHeader 
            className="pb-2 cursor-pointer" 
            onClick={() => setQuickActionsOpen(!quickActionsOpen)}
            data-testid="button-toggle-quick-actions"
          >
            <CardTitle className="text-white text-lg flex items-center justify-center w-full relative">
              <span>Quick Actions</span>
              <X className={cn("h-5 w-5 transition-transform absolute right-0", quickActionsOpen ? "rotate-0" : "rotate-45")} />
            </CardTitle>
          </CardHeader>
          {quickActionsOpen && (
            <CardContent className="pt-2 pb-3">
              <div className="grid grid-cols-2 gap-2">
                <Button onClick={() => setMode('ADD_REMINDER')} variant="secondary" className="bg-white/20 hover:bg-white/30 border-none text-white text-xs justify-center gap-1.5 h-8" data-testid="button-add-reminder">
                  <Plus className="h-3 w-3" /> Reminder
                </Button>
                <Button onClick={() => setLocation('/medications')} variant="secondary" className="bg-white/20 hover:bg-white/30 border-none text-white text-xs justify-center gap-1.5 h-8" data-testid="button-log-meds">
                  <Pill className="h-3 w-3" /> Meds
                </Button>
                <Button onClick={() => setMode('ADD_CHORE')} variant="secondary" className="bg-white/20 hover:bg-white/30 border-none text-white text-xs justify-center gap-1.5 h-8" data-testid="button-add-chore">
                  <Check className="h-3 w-3" /> Chore
                </Button>
                <Button variant="secondary" className="bg-white/20 hover:bg-white/30 border-none text-white text-xs justify-center gap-1.5 h-8" onClick={() => setLocation('/groceries')} data-testid="button-add-grocery">
                  <ShoppingCart className="h-3 w-3" /> Grocery
                </Button>
              </div>
              <ul className="text-xs space-y-2 mt-4 opacity-90 border-t border-white/10 pt-4">
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-white shadow-[0_0_8px_white]" />
                  {medicines.length} medication(s) being tracked
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-white shadow-[0_0_8px_white]" />
                  {reminders.length} upcoming reminder(s)
                </li>
              </ul>
            </CardContent>
          )}
        </Card>

        <Card className="shadow-lg border-none bg-white/50 backdrop-blur-sm overflow-hidden">
          <CardHeader className="flex flex-row items-center justify-between py-3 px-4 border-b bg-[#D2691E]/5">
            <CardTitle className="text-lg text-[#D2691E]">Today's Schedule</CardTitle>
            <Button 
              variant="ghost" 
              size="sm" 
              className="text-[#D2691E] hover:bg-[#D2691E]/10 text-xs h-7"
              onClick={() => setShowAllSchedule(!showAllSchedule)}
              data-testid="button-view-all-schedule"
            >
              {showAllSchedule ? 'Show Less' : `View All (${choreItems.length} chores)`}
            </Button>
          </CardHeader>
          <CardContent className="p-0">
            {isLoading && (
              <div className="flex items-center justify-center py-8">
                <Loader2 className="h-6 w-6 animate-spin text-[#D2691E]" />
              </div>
            )}
            <div className="divide-y divide-border">
              {displaySchedule.length === 0 && !isLoading && (
                <div className="p-6 text-center text-muted-foreground text-sm">
                  No appointments or medications for today
                </div>
              )}
              {displaySchedule.map(item => (
                <div key={`${item.type}-${item.id}`} className="flex items-center gap-3 p-4 hover:bg-muted/30 transition-all cursor-pointer group" data-testid={`card-schedule-${item.type}-${item.id}`}>
                  <div className={cn(
                    "flex h-10 w-10 items-center justify-center rounded-lg font-bold text-xs group-hover:text-white transition-all",
                    item.type === 'reminder' && "bg-[#D2691E]/10 text-[#D2691E] group-hover:bg-[#D2691E]",
                    item.type === 'chore' && item.status === 'PENDING' && "bg-amber-100 text-amber-600 group-hover:bg-amber-500",
                    item.type === 'chore' && item.status !== 'PENDING' && "bg-green-100 text-green-600 group-hover:bg-green-500",
                    item.type === 'medication' && item.status === 'TAKEN' && "bg-green-100 text-green-600 group-hover:bg-green-500",
                    item.type === 'medication' && item.status === 'PARTIAL' && "bg-amber-100 text-amber-600 group-hover:bg-amber-500",
                    item.type === 'medication' && item.status === 'PENDING' && "bg-pink-100 text-pink-600 group-hover:bg-pink-500"
                  )}>
                    {item.type === 'reminder' && <Calendar className="h-5 w-5" />}
                    {item.type === 'chore' && item.status === 'PENDING' && <Clock className="h-5 w-5" />}
                    {item.type === 'chore' && item.status !== 'PENDING' && <Check className="h-5 w-5" />}
                    {item.type === 'medication' && item.status === 'TAKEN' && <Check className="h-5 w-5" />}
                    {item.type === 'medication' && item.status === 'PARTIAL' && <Pill className="h-5 w-5" />}
                    {item.type === 'medication' && item.status === 'PENDING' && <Pill className="h-5 w-5" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <h4 className="font-semibold text-sm truncate group-hover:text-[#D2691E]">{item.title}</h4>
                    <p className="text-xs text-muted-foreground flex items-center gap-1 mt-0.5 flex-wrap">
                      {item.time && <><Clock className="h-3 w-3" /> {item.time}</>}
                      {item.type === 'medication' && item.doses && item.doses.length > 0 && (
                        <span className="flex items-center gap-2">
                          {item.doses.map((dose, idx) => (
                            <button
                              key={dose.time}
                              onClick={(e) => handleDoseClick(item.medicineId!, dose.time, dose.taken, e)}
                              disabled={createMedicineLog.isPending}
                              className={cn(
                                "inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium transition-all",
                                dose.taken 
                                  ? "bg-green-100 text-green-700 cursor-default" 
                                  : "bg-pink-100 text-pink-700 hover:bg-pink-200 cursor-pointer"
                              )}
                              data-testid={`button-dose-${item.id}-${dose.time}`}
                            >
                              {dose.time} {dose.taken ? '✓' : '○'}
                            </button>
                          ))}
                        </span>
                      )}
                      {item.type === 'chore' && (
                        <span className="flex items-center gap-1">
                          <span className="font-medium text-[#D2691E]">{item.assignedName || 'Unassigned'}</span>
                          <span className="capitalize">• {(item.status || 'pending').toLowerCase()}</span>
                        </span>
                      )}
                      {!item.time && item.type !== 'medication' && item.type !== 'chore' && 'All day'}
                    </p>
                  </div>
                  <Badge 
                    variant="secondary" 
                    className={cn(
                      "text-[10px] font-medium h-5 rounded-md capitalize",
                      item.type === 'chore' && item.status === 'PENDING' && "bg-amber-100 text-amber-700",
                      item.type === 'chore' && item.status !== 'PENDING' && "bg-green-100 text-green-700",
                      item.type === 'medication' && item.status === 'TAKEN' && "bg-green-100 text-green-700",
                      item.type === 'medication' && item.status === 'PARTIAL' && "bg-amber-100 text-amber-700",
                      item.type === 'medication' && item.status === 'PENDING' && "bg-pink-100 text-pink-700"
                    )}
                  >
                    {item.type === 'medication' ? (item.status === 'TAKEN' ? 'All Taken' : item.status === 'PARTIAL' ? 'Partial' : 'Pending') : item.type}
                  </Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="bg-gradient-to-br from-[#D2691E] to-[#B8581A] border-none shadow-xl text-white overflow-hidden" data-testid="card-smart-input">
        <CardHeader className="pb-2">
          <CardTitle className="text-white text-lg flex items-center gap-2">
            <Sparkles className="h-5 w-5" /> Quick Add with AI
          </CardTitle>
          <CardDescription className="text-white/80">
            Type or speak to add chores, reminders, medications, or groceries
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="bg-white rounded-xl p-4">
            <Textarea
              value={smartInputText}
              onChange={(e) => setSmartInputText(e.target.value)}
              placeholder="Try: 'Tomorrow buy milk and eggs, remind me to take vitamins at 8am, kids need to do homework by 5pm, doctor appointment Thursday at 2pm'"
              className="border-0 resize-none text-gray-800 placeholder:text-gray-400 focus-visible:ring-0 min-h-[80px]"
              disabled={isProcessing}
              data-testid="input-smart-text"
            />
            <div className="flex justify-end gap-2 mt-3 pt-3 border-t">
              <Button
                variant="outline"
                size="sm"
                onClick={toggleVoiceInput}
                disabled={isProcessing || !speechSupported}
                className={cn(
                  "gap-2",
                  isRecording && "bg-red-50 border-red-300 text-red-600 animate-pulse"
                )}
                title={speechSupported ? (isRecording ? 'Stop recording' : 'Start voice input') : 'Voice input not supported'}
                data-testid="button-voice-input"
              >
                {isRecording ? <MicOff className="h-4 w-4" /> : <Mic className="h-4 w-4" />}
                {isRecording ? 'Stop' : 'Speak'}
              </Button>
              <Button
                size="sm"
                onClick={processSmartInput}
                disabled={isProcessing || !smartInputText.trim()}
                className="gap-2 bg-violet-600 hover:bg-violet-700"
                data-testid="button-process-input"
              >
                <Send className="h-4 w-4" />
                {isProcessing ? 'Processing...' : 'Add Items'}
              </Button>
            </div>
          </div>
          
          {lastResult && (
            <div className={cn(
              "rounded-lg p-3 text-sm border",
              lastResult.success ? "bg-[#D2691E] text-white border-[#D2691E]" : "bg-red-100 text-red-800 border-red-300"
            )} data-testid="text-result-message">
              <p>{lastResult.message}</p>
              {lastResult.items && lastResult.items.length > 0 && (
                <div className="flex flex-wrap gap-2 mt-2">
                  {lastResult.items.map((item, idx) => (
                    <Badge 
                      key={idx} 
                      variant="secondary" 
                      className={cn(
                        "text-xs",
                        item.type === 'chore' && "bg-amber-100 text-amber-800",
                        item.type === 'reminder' && "bg-blue-100 text-blue-800",
                        item.type === 'medication' && "bg-green-100 text-green-800",
                        item.type === 'grocery' && "bg-[#D2691E]/10 text-[#D2691E]"
                      )}
                    >
                      {item.type}: {item.title}
                    </Badge>
                  ))}
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        <Card className="shadow-sm border-l-4 border-l-[#D2691E]">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Next Reminder</CardTitle>
            <Calendar className="h-4 w-4 text-[#D2691E]" />
          </CardHeader>
          <CardContent>
            <div className="text-xl font-bold truncate">{reminders[0]?.title || 'None scheduled'}</div>
            <p className="text-[10px] text-muted-foreground mt-1 flex items-center gap-1">
              <Clock className="h-3 w-3" /> 
              {reminders[0]?.startTime ? format(new Date(reminders[0].startTime), "h:mm a") : 'N/A'}
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// wpclife-frontend/src/app/features/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink, Router } from '@angular/router';
import { SidebarComponent } from '../../shared/components/sidebar/sidebar.component';
import { ApiService } from '../../core/services/api.service';
import { AuthService } from '../../core/services/auth.service';
import { HttpClient } from '@angular/common/http';
import { Chore } from '../../shared/models/chore.model';
import { CalendarEvent } from '../../shared/models/calendar.model';
import { Medication } from '../../shared/models/medication.model';
import { GroceryItem } from '../../shared/models/grocery.model';
import { environment } from '../../../environments/environment';

interface ParsedItem {
  type: string;
  title: string;
}

interface ScheduleResponse {
  message: string;
  items: ParsedItem[];
  choresCreated: number;
  remindersCreated: number;
  medicationsCreated: number;
  groceriesCreated: number;
}

interface MedicineLog {
  id: string;
  medicineId: string;
  scheduledTime: string;
  takenAt: string;
  status: string;
}

interface DoseInfo {
  time: string;
  taken: boolean;
}

interface ScheduleItem {
  id: string;
  type: 'reminder' | 'chore' | 'medication';
  title: string;
  time?: string;
  status?: string;
  assignedTo?: string;
  assignedName?: string;
  medicineId?: string;
  doses?: DoseInfo[];
}

interface FamilyMember {
  id: string;
  name: string;
  avatar?: string;
}

declare var webkitSpeechRecognition: any;

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, SidebarComponent],
  template: `
    <div class="layout">
      <app-sidebar></app-sidebar>
      
      <main class="main-content">
        <header class="mobile-header">
          <h1>Blueberry</h1>
        </header>
        <div class="welcome-section">
          <h2>Welcome back, {{ userName }}</h2>
          <p>Here's what's happening with your family today</p>
        </div>
        
        <div class="dashboard-grid-top">
          <section class="card quick-actions-card" data-testid="card-quick-actions">
            <div class="quick-actions-header" (click)="quickActionsOpen = !quickActionsOpen" data-testid="button-toggle-quick-actions">
              <h3>Quick Actions</h3>
              <span class="toggle-icon" [class.open]="quickActionsOpen">+</span>
            </div>
            @if (quickActionsOpen) {
              <div class="quick-actions-content">
                <div class="quick-actions-grid">
                  <button class="quick-action-btn" routerLink="/calendar" data-testid="button-add-reminder">
                    <span class="icon">+</span> Reminder
                  </button>
                  <button class="quick-action-btn" routerLink="/medications" data-testid="button-log-meds">
                    <span class="icon">💊</span> Meds
                  </button>
                  <button class="quick-action-btn" routerLink="/chores" data-testid="button-add-chore">
                    <span class="icon">✓</span> Chore
                  </button>
                  <button class="quick-action-btn" routerLink="/groceries" data-testid="button-add-grocery">
                    <span class="icon">🛒</span> Grocery
                  </button>
                </div>
                <ul class="quick-stats">
                  <li><span class="dot"></span> {{ medications.length }} medication(s) being tracked</li>
                  <li><span class="dot"></span> {{ todayReminders.length }} upcoming reminder(s)</li>
                </ul>
              </div>
            }
          </section>
          
          <section class="card todays-schedule-card" data-testid="card-todays-schedule">
            <div class="schedule-header">
              <h3>Today's Schedule</h3>
              <button class="view-all-btn" (click)="showAllSchedule = !showAllSchedule" data-testid="button-view-all-schedule">
                {{ showAllSchedule ? 'Show Less' : 'View All (' + todayChores.length + ' chores)' }}
              </button>
            </div>
            @if (isLoading) {
              <div class="loading-state">Loading...</div>
            } @else if (displaySchedule.length === 0) {
              <p class="empty-state">No appointments or medications for today</p>
            } @else {
              <div class="schedule-list">
                @for (item of displaySchedule; track item.id) {
                  <div class="schedule-item" [attr.data-testid]="'card-schedule-' + item.type + '-' + item.id">
                    <div class="schedule-icon" [class]="'icon-' + item.type + '-' + (item.status || 'pending').toLowerCase()">
                      @if (item.type === 'reminder') { 📅 }
                      @else if (item.type === 'chore' && item.status === 'PENDING') { ⏰ }
                      @else if (item.type === 'chore') { ✓ }
                      @else if (item.type === 'medication' && item.status === 'TAKEN') { ✓ }
                      @else { 💊 }
                    </div>
                    <div class="schedule-details">
                      <h4>{{ item.title }}</h4>
                      <p class="schedule-meta">
                        @if (item.time) {
                          <span class="time">🕐 {{ item.time }}</span>
                        }
                        @if (item.type === 'medication' && item.doses && item.doses.length > 0) {
                          <span class="doses">
                            @for (dose of item.doses; track dose.time) {
                              <button 
                                class="dose-btn" 
                                [class.taken]="dose.taken"
                                (click)="handleDoseClick(item.medicineId!, dose.time, dose.taken, $event)"
                                [attr.data-testid]="'button-dose-' + item.id + '-' + dose.time"
                              >
                                {{ dose.time }} {{ dose.taken ? '✓' : '○' }}
                              </button>
                            }
                          </span>
                        }
                        @if (item.type === 'chore') {
                          <span class="chore-info">
                            <span class="assigned-name">{{ item.assignedName || 'Unassigned' }}</span>
                            <span class="status">• {{ (item.status || 'pending').toLowerCase() }}</span>
                          </span>
                        }
                      </p>
                    </div>
                    <span class="schedule-badge" [class]="'badge-' + item.type + '-' + (item.status || 'pending').toLowerCase()">
                      @if (item.type === 'medication') {
                        {{ item.status === 'TAKEN' ? 'All Taken' : item.status === 'PARTIAL' ? 'Partial' : 'Pending' }}
                      } @else {
                        {{ item.type }}
                      }
                    </span>
                  </div>
                }
              </div>
            }
          </section>
        </div>
        
        @if (isGuardian) {
          <section class="smart-input-section" data-testid="section-smart-input">
            <div class="smart-input-card">
              <h3>✨ Quick Add with AI</h3>
              <p class="hint">Type or speak to add chores, reminders, medications, or groceries</p>
              
              <div class="input-container">
                <textarea
                  [(ngModel)]="smartInputText"
                  placeholder="Try: 'Tomorrow buy milk and eggs, remind me to take vitamins at 8am, kids need to do homework by 5pm, doctor appointment Thursday at 2pm'"
                  rows="3"
                  [disabled]="isProcessing"
                  data-testid="input-smart-text"
                ></textarea>
                
                <div class="input-actions">
                  <button 
                    class="voice-btn" 
                    (click)="toggleVoiceInput()"
                    [class.recording]="isRecording"
                    [disabled]="isProcessing || !speechSupported"
                    [title]="speechSupported ? (isRecording ? 'Stop recording' : 'Start voice input') : 'Voice input not supported in this browser'"
                    data-testid="button-voice-input"
                  >
                    {{ isRecording ? '🔴 Stop' : '🎤 Speak' }}
                  </button>
                  
                  <button 
                    class="send-btn" 
                    (click)="processSmartInput()"
                    [disabled]="isProcessing || !smartInputText.trim()"
                    data-testid="button-process-input"
                  >
                    {{ isProcessing ? 'Processing...' : 'Add Items' }}
                  </button>
                </div>
              </div>
              
              @if (lastResult) {
                <div class="result-message" [class.success]="lastResult.success" data-testid="text-result-message">
                  <span>{{ lastResult.message }}</span>
                  @if (lastResult.items && lastResult.items.length > 0) {
                    <div class="created-items">
                      @for (item of lastResult.items; track item.title) {
                        <span class="item-badge" [class]="item.type">{{ item.type }}: {{ item.title }}</span>
                      }
                    </div>
                  }
                </div>
              }
            </div>
          </section>
        }
      </main>
    </div>
  `,
  styles: [`
    .layout {
      display: flex;
      min-height: 100vh;
    }
    
    .main-content {
      flex: 1;
      margin-left: 250px;
      padding: 2rem;
      background: var(--background);
    }
    
    .mobile-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 0.75rem 1rem;
      background: white;
      border-bottom: 1px solid var(--border);
      margin: -2rem -2rem 1.5rem -2rem;
      
      h1 {
        font-size: 1.125rem;
        font-weight: 600;
        color: var(--primary);
        margin: 0;
      }
    }
    
    .welcome-section {
      margin-bottom: 1.5rem;
      
      h2 {
        margin-bottom: 0.25rem;
      }
      
      p {
        color: var(--text-secondary);
      }
    }
    
    .dashboard-grid-top {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 1.5rem;
      margin-bottom: 1.5rem;
    }
    
    .card {
      background: white;
      border-radius: 0.75rem;
      padding: 1.5rem;
      box-shadow: var(--shadow);
    }
    
    .quick-actions-card {
      background: linear-gradient(135deg, #D2691E 0%, #E8A060 100%);
      color: white;
      padding: 0;
      overflow: hidden;
    }
    
    .quick-actions-header {
      padding: 1rem 1.5rem;
      display: flex;
      justify-content: center;
      align-items: center;
      cursor: pointer;
      position: relative;
      
      h3 {
        margin: 0;
        font-size: 1.125rem;
      }
      
      .toggle-icon {
        position: absolute;
        right: 1.5rem;
        font-size: 1.25rem;
        transition: transform 0.2s;
        
        &.open {
          transform: rotate(45deg);
        }
      }
    }
    
    .quick-actions-content {
      padding: 0.5rem 1.5rem 1.5rem;
      border-top: 1px solid rgba(255,255,255,0.1);
    }
    
    .quick-actions-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 0.5rem;
    }
    
    .quick-action-btn {
      background: rgba(255,255,255,0.2);
      border: none;
      color: white;
      padding: 0.5rem;
      border-radius: 0.5rem;
      font-size: 0.75rem;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 0.375rem;
      transition: background 0.2s;
      
      &:hover {
        background: rgba(255,255,255,0.3);
      }
      
      .icon {
        font-size: 0.875rem;
      }
    }
    
    .quick-stats {
      list-style: none;
      padding: 0;
      margin: 1rem 0 0;
      font-size: 0.75rem;
      opacity: 0.9;
      border-top: 1px solid rgba(255,255,255,0.1);
      padding-top: 1rem;
      
      li {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        margin-bottom: 0.5rem;
      }
      
      .dot {
        width: 0.375rem;
        height: 0.375rem;
        border-radius: 50%;
        background: white;
        box-shadow: 0 0 8px white;
      }
    }
    
    .todays-schedule-card {
      background: rgba(255,255,255,0.5);
      backdrop-filter: blur(10px);
      padding: 0;
      overflow: hidden;
    }
    
    .schedule-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 0.75rem 1rem;
      border-bottom: 1px solid var(--border);
      background: rgba(210, 105, 30, 0.05);
      
      h3 {
        margin: 0;
        font-size: 1.125rem;
        color: #D2691E;
      }
    }
    
    .view-all-btn {
      background: none;
      border: none;
      color: #D2691E;
      font-size: 0.75rem;
      cursor: pointer;
      padding: 0.25rem 0.5rem;
      border-radius: 0.25rem;
      
      &:hover {
        background: rgba(210, 105, 30, 0.1);
      }
    }
    
    .loading-state {
      padding: 2rem;
      text-align: center;
      color: #D2691E;
    }
    
    .empty-state {
      padding: 1.5rem;
      text-align: center;
      color: var(--text-secondary);
      font-size: 0.875rem;
    }
    
    .schedule-list {
      max-height: 300px;
      overflow-y: auto;
    }
    
    .schedule-item {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 1rem;
      border-bottom: 1px solid var(--border);
      cursor: pointer;
      transition: background 0.2s;
      
      &:hover {
        background: rgba(0,0,0,0.02);
      }
      
      &:last-child {
        border-bottom: none;
      }
    }
    
    .schedule-icon {
      width: 2.5rem;
      height: 2.5rem;
      border-radius: 0.5rem;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 1.25rem;
      
      &.icon-reminder-pending { background: rgba(210, 105, 30, 0.1); }
      &.icon-chore-pending { background: #fef3c7; }
      &.icon-chore-completed { background: #dcfce7; }
      &.icon-medication-taken { background: #dcfce7; }
      &.icon-medication-partial { background: #fef3c7; }
      &.icon-medication-pending { background: #fce7f3; }
    }
    
    .schedule-details {
      flex: 1;
      min-width: 0;
      
      h4 {
        margin: 0 0 0.25rem;
        font-size: 0.875rem;
        font-weight: 600;
      }
    }
    
    .schedule-meta {
      margin: 0;
      font-size: 0.75rem;
      color: var(--text-secondary);
      display: flex;
      align-items: center;
      flex-wrap: wrap;
      gap: 0.5rem;
    }
    
    .doses {
      display: flex;
      gap: 0.5rem;
    }
    
    .dose-btn {
      display: inline-flex;
      align-items: center;
      gap: 0.25rem;
      padding: 0.125rem 0.375rem;
      border-radius: 0.25rem;
      font-size: 0.625rem;
      font-weight: 500;
      border: none;
      cursor: pointer;
      transition: all 0.2s;
      background: #fce7f3;
      color: #be185d;
      
      &:hover:not(.taken) {
        background: #fbcfe8;
      }
      
      &.taken {
        background: #dcfce7;
        color: #166534;
        cursor: default;
      }
    }
    
    .chore-info {
      display: flex;
      align-items: center;
      gap: 0.25rem;
    }
    
    .assigned-name {
      font-weight: 500;
      color: #D2691E;
    }
    
    .status {
      text-transform: capitalize;
    }
    
    .schedule-badge {
      padding: 0.25rem 0.5rem;
      border-radius: 0.375rem;
      font-size: 0.625rem;
      font-weight: 500;
      text-transform: capitalize;
      
      &.badge-reminder-pending { background: rgba(210, 105, 30, 0.1); color: #D2691E; }
      &.badge-chore-pending { background: #fef3c7; color: #92400e; }
      &.badge-chore-completed { background: #dcfce7; color: #166534; }
      &.badge-medication-taken { background: #dcfce7; color: #166534; }
      &.badge-medication-partial { background: #fef3c7; color: #92400e; }
      &.badge-medication-pending { background: #fce7f3; color: #be185d; }
    }
    
    .smart-input-section {
      margin-top: 1.5rem;
    }
    
    .smart-input-card {
      background: linear-gradient(135deg, #D2691E 0%, #B8581A 100%);
      border-radius: 1rem;
      padding: 1.5rem;
      color: white;
      box-shadow: 0 10px 40px rgba(210, 105, 30, 0.3);
      
      h3 {
        margin: 0 0 0.25rem;
        font-size: 1.25rem;
      }
      
      .hint {
        opacity: 0.8;
        font-size: 0.875rem;
        margin-bottom: 1rem;
      }
    }
    
    .input-container {
      background: white;
      border-radius: 0.75rem;
      padding: 1rem;
      
      textarea {
        width: 100%;
        border: none;
        resize: none;
        font-family: inherit;
        font-size: 0.9rem;
        color: #333;
        
        &:focus {
          outline: none;
        }
        
        &::placeholder {
          color: #9ca3af;
        }
      }
    }
    
    .input-actions {
      display: flex;
      gap: 0.75rem;
      margin-top: 0.75rem;
      justify-content: flex-end;
    }
    
    .voice-btn, .send-btn {
      padding: 0.625rem 1.25rem;
      border-radius: 0.5rem;
      font-weight: 500;
      cursor: pointer;
      transition: all 0.2s;
    }
    
    .voice-btn {
      background: #f3f4f6;
      border: 1px solid #d1d5db;
      color: #374151;
      
      &:hover:not(:disabled) {
        background: #e5e7eb;
      }
      
      &.recording {
        background: #fef2f2;
        border-color: #ef4444;
        color: #dc2626;
        animation: pulse 1.5s infinite;
      }
      
      &:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }
    }
    
    @keyframes pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.7; }
    }
    
    .send-btn {
      background: #D2691E;
      border: none;
      color: white;
      
      &:hover:not(:disabled) {
        background: #B8581A;
      }
      
      &:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }
    }
    
    .result-message {
      margin-top: 1rem;
      padding: 0.75rem 1rem;
      border-radius: 0.5rem;
      background: rgba(255,255,255,0.2);
      font-size: 0.875rem;
      
      &.success {
        background: rgba(34, 197, 94, 0.2);
      }
    }
    
    .created-items {
      margin-top: 0.5rem;
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
    }
    
    .item-badge {
      padding: 0.25rem 0.5rem;
      border-radius: 0.25rem;
      font-size: 0.75rem;
      background: rgba(255,255,255,0.3);
      
      &.chore { background: #fef3c7; color: #92400e; }
      &.reminder { background: #dbeafe; color: #1e40af; }
      &.medication { background: #dcfce7; color: #166534; }
      &.grocery { background: #e0e7ff; color: #4338ca; }
    }
    
    @media (max-width: 1024px) {
      .main-content {
        margin-left: 0;
      }
      
      .dashboard-grid-top {
        grid-template-columns: 1fr;
      }
    }
    
    @media (max-width: 768px) {
      .main-content {
        padding: 1rem;
      }
    }
  `]
})
export class DashboardComponent implements OnInit {
  userName = 'User';
  isGuardian = false;
  quickActionsOpen = false;
  showAllSchedule = false;
  isLoading = true;
  
  todayReminders: any[] = [];
  todayChores: Chore[] = [];
  pendingChores: Chore[] = [];
  medications: Medication[] = [];
  medicineLogs: MedicineLog[] = [];
  members: FamilyMember[] = [];
  groceryItems: GroceryItem[] = [];
  pendingGroceries = 0;
  leaderboardEntries: { userId: string; userName: string; points: number }[] = [];
  
  displaySchedule: ScheduleItem[] = [];
  
  smartInputText = '';
  isProcessing = false;
  isRecording = false;
  speechSupported = false;
  lastResult: { success: boolean; message: string; items?: ParsedItem[] } | null = null;
  
  private recognition: any;
  private familyId: string | null = null;

  constructor(
    private apiService: ApiService,
    private authService: AuthService,
    private http: HttpClient,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.checkSpeechSupport();
    this.loadUserData();
  }

  private checkSpeechSupport(): void {
    this.speechSupported = 'webkitSpeechRecognition' in window;
    if (this.speechSupported) {
      this.recognition = new webkitSpeechRecognition();
      this.recognition.continuous = true;
      this.recognition.interimResults = true;
      this.recognition.lang = 'en-US';
      
      this.recognition.onresult = (event: any) => {
        let transcript = '';
        for (let i = event.resultIndex; i < event.results.length; i++) {
          transcript += event.results[i][0].transcript;
        }
        this.smartInputText = transcript;
      };
      
      this.recognition.onerror = () => {
        this.isRecording = false;
      };
      
      this.recognition.onend = () => {
        this.isRecording = false;
      };
    }
  }

  private loadUserData(): void {
    this.http.get<any>(`${environment.apiUrl}/api/auth/me`, { withCredentials: true })
      .subscribe({
        next: (response) => {
          if (response.authenticated && response.user) {
            this.userName = response.user.name || 'User';
            this.isGuardian = !response.user.isChild;
            this.familyId = response.familyId;
            this.loadDashboardData();
          }
        },
        error: () => {
          this.isLoading = false;
        }
      });
  }

  private loadDashboardData(): void {
    if (!this.familyId) {
      this.isLoading = false;
      return;
    }

    const today = new Date();
    const todayStr = today.toISOString().split('T')[0];
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    this.http.get<FamilyMember[]>(`${environment.apiUrl}/api/families/${this.familyId}/members`, { withCredentials: true })
      .subscribe(members => this.members = members || []);

    this.http.get<any[]>(`${environment.apiUrl}/api/families/${this.familyId}/reminders`, { withCredentials: true })
      .subscribe({
        next: (reminders) => {
          this.todayReminders = (reminders || []).filter(r => {
            if (!r.startTime) return false;
            const reminderDate = new Date(r.startTime);
            return reminderDate >= today && reminderDate < tomorrow;
          });
          this.buildSchedule();
        }
      });

    this.http.get<Chore[]>(`${environment.apiUrl}/api/families/${this.familyId}/chores`, { withCredentials: true })
      .subscribe({
        next: (chores) => {
          this.pendingChores = (chores || []).filter(c => c.status === 'PENDING');
          this.todayChores = (chores || []).filter(c => c.dueDate === todayStr);
          this.calculateLeaderboard(chores || []);
          this.buildSchedule();
        }
      });

    this.http.get<Medication[]>(`${environment.apiUrl}/api/families/${this.familyId}/medicines`, { withCredentials: true })
      .subscribe({
        next: (meds) => {
          this.medications = meds || [];
          this.buildSchedule();
        }
      });

    this.http.get<MedicineLog[]>(`${environment.apiUrl}/api/families/${this.familyId}/medicine-logs`, { withCredentials: true })
      .subscribe({
        next: (logs) => {
          this.medicineLogs = logs || [];
          this.buildSchedule();
        }
      });

    this.http.get<GroceryItem[]>(`${environment.apiUrl}/api/families/${this.familyId}/groceries`, { withCredentials: true })
      .subscribe({
        next: (items) => {
          this.groceryItems = items || [];
          this.pendingGroceries = this.groceryItems.filter(i => !i.purchased).length;
          this.isLoading = false;
        },
        error: () => {
          this.isLoading = false;
        }
      });
  }

  private buildSchedule(): void {
    const todayStr = new Date().toISOString().split('T')[0];
    
    const reminderItems: ScheduleItem[] = this.todayReminders.map(r => ({
      id: r.id,
      type: 'reminder' as const,
      title: r.title,
      time: r.startTime ? new Date(r.startTime).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }) : undefined,
      status: 'PENDING'
    }));

    const medicationItems: ScheduleItem[] = this.medications
      .filter(m => this.isMedicationActiveToday(m))
      .map(m => {
        const schedule = m.schedule as { type?: string; times?: string[] } | null;
        const times = schedule?.times || [];
        const dosesInfo = times.map(time => ({
          time,
          taken: this.isDoseTakenToday(m.id, time)
        }));
        const allTaken = dosesInfo.every(d => d.taken);
        const someTaken = dosesInfo.some(d => d.taken);
        return {
          id: m.id,
          type: 'medication' as const,
          title: m.name,
          medicineId: m.id,
          doses: dosesInfo,
          status: allTaken ? 'TAKEN' : (someTaken ? 'PARTIAL' : 'PENDING')
        };
      });

    const choreItems: ScheduleItem[] = this.todayChores.map(c => {
      const member = this.members.find(m => m.id === c.assignedTo);
      return {
        id: c.id,
        type: 'chore' as const,
        title: c.title,
        status: c.status || 'PENDING',
        assignedTo: c.assignedTo || undefined,
        assignedName: member?.name
      };
    });

    const priorityItems = [...reminderItems, ...medicationItems];
    this.displaySchedule = this.showAllSchedule ? [...priorityItems, ...choreItems] : priorityItems;
  }

  private isMedicationActiveToday(medicine: Medication): boolean {
    if (!medicine.active) return false;
    const todayStr = new Date().toISOString().split('T')[0];
    if (medicine.startDate && todayStr < medicine.startDate) return false;
    if (medicine.endDate && todayStr > medicine.endDate) return false;
    return true;
  }

  private isDoseTakenToday(medicineId: string, scheduledTime: string): boolean {
    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);
    return this.medicineLogs.some(log => {
      const logDate = new Date(log.takenAt);
      logDate.setHours(0, 0, 0, 0);
      return log.medicineId === medicineId && 
             log.scheduledTime === scheduledTime && 
             logDate.getTime() === todayStart.getTime();
    });
  }

  handleDoseClick(medicineId: string, scheduledTime: string, alreadyTaken: boolean, event: Event): void {
    event.stopPropagation();
    if (alreadyTaken || !this.familyId) return;

    this.http.post(`${environment.apiUrl}/api/families/${this.familyId}/medicine-logs`, {
      medicineId,
      takenAt: new Date().toISOString(),
      scheduledTime,
      status: 'TAKEN'
    }, { withCredentials: true }).subscribe({
      next: () => {
        this.loadDashboardData();
      }
    });
  }

  private calculateLeaderboard(chores: Chore[]): void {
    const pointsMap = new Map<string, { name: string; points: number }>();
    
    chores.filter(c => c.status === 'COMPLETED' && c.assignedTo).forEach(chore => {
      const current = pointsMap.get(chore.assignedTo!) || { name: '', points: 0 };
      const member = this.members.find(m => m.id === chore.assignedTo);
      current.name = member?.name || 'Unknown';
      current.points += chore.points || 0;
      pointsMap.set(chore.assignedTo!, current);
    });
    
    this.leaderboardEntries = Array.from(pointsMap.entries())
      .map(([userId, data]) => ({ userId, userName: data.name, points: data.points }))
      .sort((a, b) => b.points - a.points)
      .slice(0, 5);
  }

  formatTime(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  }

  toggleVoiceInput(): void {
    if (this.isRecording) {
      this.recognition?.stop();
      this.isRecording = false;
    } else {
      this.smartInputText = '';
      this.recognition?.start();
      this.isRecording = true;
    }
  }

  processSmartInput(): void {
    if (!this.smartInputText.trim() || this.isProcessing) return;
    
    this.isProcessing = true;
    this.lastResult = null;
    
    this.http.post<ScheduleResponse>(`${environment.apiUrl}/api/ai/schedule`, {
      text: this.smartInputText,
      familyId: this.familyId,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone
    }, { withCredentials: true }).subscribe({
      next: (data) => {
        const totalCreated = (data.choresCreated || 0) + (data.remindersCreated || 0) + (data.medicationsCreated || 0) + (data.groceriesCreated || 0);
        
        this.lastResult = {
          success: totalCreated > 0,
          message: data.message,
          items: data.items
        };
        
        if (totalCreated > 0) {
          this.smartInputText = '';
          this.loadDashboardData();
        }
        
        this.isProcessing = false;
        
        setTimeout(() => {
          this.lastResult = null;
        }, 3000);
      },
      error: (error) => {
        this.lastResult = {
          success: false,
          message: 'Failed to process your request. Please try again.'
        };
        this.isProcessing = false;
      }
    });
  }
}
